### PR TITLE
s/publicKey/key Link parameter

### PR DESCRIPTION
**Pull request by skansal-plaid**
Addresses https://github.com/plaid/react-plaid-link/pull/71#discussion_r374869204

### CODE REVIEW

**Comment by skansal-plaid** [comment]
We should make sure the local setup works, it currently does not work for me. Please address https://github.com/plaid/react-plaid-link/pull/71#issuecomment-582071557.

**Comment by skansal-plaid** [comment]
Thanks @jacksiegel.

@pbernasconi We will need your approval before we can merge this PR.

**Comment by jacksiegel** [comment]
@skansal-plaid I just realized this is a breaking change... Perhaps it is better to keep this as `publicKey` (and update the README accordingly) to avoid breaking all of the users?

**Comment by skansal-plaid** [comment]
@jacksiegel Good catch, yeah let me update the README instead. I will add a comment about why we want to keep the publicKey param as is (and different from plaid docs) -- to avoid breaking change for react-plaid-link customers.

When we release a new major version of react-plaid-link, we should rename the publicKey param to key so we match the Plaid docs.

**Pull request closed without merging**
