### PR TITLE
Ensure Plaid link-initialize.js is embedded only once

### LINKED ISSUE #107: Warning about link-initialize.js script embedded more than once
I'm submitting this issue as reopening #103 
I updated to 2.1.2 as @timruffles recommended and I'm still seeing the same issue where the link-initalize.js is embedded more than once if you hit back and then forward in the browser and come back to the page where react-plaid-link is used. See screenshot of warning:
image
Also I looked at #86 again and this is a different issue. I've never experience the initial load failing. What I'm seeing is that the Plaid link-initialize.js is loaded more than once.
We've identified an issue this is causing in our app were the onSuccess callback is called twice.

### PR DESCRIPTION
**Pull request by rblakejohnson**
This fixes #107 by upgrading `react-script-hook` to 1.1.0 and using the `checkIfExisting` flag

### CODE REVIEW

**Comment by nachaos** [comment]
I've tested the fix and can confirm it fixes the issue. @pbernasconi can this be reviewed and merged if possible? Thanks.

**Comment by goleary** [comment]
Would be lovely if this could be merged and the updated lib published.

**Comment by alexandrasmith00** [comment]
Also waiting for this to be updated

**Comment by Maushundb** [comment]
+1 on this, please merge asap. Experiencing issues caused by this :(

**Comment by felipearosemena** [comment]
Same here!

**Comment by Maushundb** [comment]
@felipearosemena If you're using yarn, you can fork the package, add this change, and in your package.json do

"react-plaid-link": "https://github.com/your-org/react-plaid-link#master"

Probably a similar thing you can do for npm.

https://www.npmjs.com/package/patch-package is also an option but not sure it'll let you update the react-script hook dependency.

**Comment by felipearosemena** [comment]
Thank you @Maushundb !

**Comment by felipearosemena** [comment]
So I tried, @Maushundb 's recommendation, but no luck. Only after forking realized that the package also needs to be built.. at this point it's probably not worth the effort instrumenting that as well.

Would hugely appreciate if this update could get merged & released 🙏

**Comment by Maushundb** [comment]
> Only after forking realized that the package also needs to be built.. at this point it's probably not worth the effort instrumenting that as well.

Yeah just run the build script, and remove the output from `.gitignore` and it should work :)

**Comment by felipearosemena** [comment]
@Maushundb 🤦 of course.. thanks for the tip! that worked beautifully 🚀

**Pull request merged**
