### PR TITLE
fix onSuccess callback dependencies array firing

### PR DESCRIPTION
**Pull request by arkatriymfalnaya**

### CODE REVIEW

**Comment by massimogiolitti** [comment]
this fixed PlaidLinkOnSuccess not being able to be imported for me.

**Review by skylarmb — CHANGES_REQUESTED** [review]
hi there @arkatriymfalnaya 

1. Could you please discard irrelevant changes and files? Please discard changes to Changelog, package-lock.json, package.json, etc
2. Is there a reason you only added onSuccess? wondering if we should add the other callbacks as dependencies as well.

**Comment by massimogiolitti** [comment]
@skylarmb for me onSuccess was the only import not working.

**Comment by skylarmb** [comment]
author did not clean up PR to discard irrelevant changes, closing

**Pull request closed without merging**
